# Generated by Django 3.1.4 on 2021-02-01 16:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulletin_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="description",
            field=models.TextField(default="text", verbose_name="description"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
