# Generated by Django 3.1.4 on 2021-02-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulletin_board", "0002_auto_20210201_2051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="views",
            field=models.IntegerField(default=0, editable=False, verbose_name="views"),
        ),
    ]
